"""fix session timestamp

Revision ID: d4750b9e7df8
Revises: 7f89b5044206
Create Date: 2026-04-11 20:58:07.663006

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4750b9e7df8"
down_revision: Union[str, Sequence[str], None] = "7f89b5044206"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE sessions SET last_active = NOW() WHERE last_active IS NULL")
    op.alter_column(
        "sessions",
        "last_active",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "last_active",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###
