"""add database index and missing attribute

Revision ID: e7cef40b95f7
Revises: fab5b5f39e7d
Create Date: 2026-04-04 19:56:08.434487

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7cef40b95f7"
down_revision: Union[str, Sequence[str], None] = "fab5b5f39e7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    # ### end Alembic commands ###
