"""change user schema

Revision ID: eef4fdf77d97
Revises: ab5b74bea47b
Create Date: 2026-04-18 19:49:04.177864

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eef4fdf77d97"
down_revision: Union[str, Sequence[str], None] = "ab5b74bea47b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill any pre-existing NULL created_at rows so the NOT NULL
    # constraint can apply cleanly on databases that predate this column
    # being populated.
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # ### end Alembic commands ###
